/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Daniele Cocchi (https://sketchfab.com/Cocchi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-homer-from-the-simpsons-low-poly-07ca14d6100944b89cc83b207d258925
Title: The Homer from The Simpsons Low-Poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/the_homer_from_the_simpsons_low-poly.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={11}>
        <group
          position={[2, -1.355, -2.971]}
          rotation={[-0.061, 0, -Math.PI / 2]}
          scale={[0.569, 0.195, 0.569]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder18_phong2_0.geometry}
            material={materials.phong2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder18_lambert4_0.geometry}
            material={materials.lambert4}
          />
        </group>
        <group
          position={[1.535, 0.245, -0.063]}
          rotation={[0.234, 0.224, -0.171]}
          scale={[0.078, 0.078, 0.311]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube22_blinn11_0.geometry}
            material={materials.blinn11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube22_oceanShader5_0.geometry}
            material={materials.oceanShader5}
          />
        </group>
        <group
          position={[-1.508, 0.245, -0.063]}
          rotation={[0.187, -0.188, -0.058]}
          scale={[0.078, 0.078, 0.311]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube23_blinn11_0.geometry}
            material={materials.blinn11}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube23_oceanShader4_0.geometry}
            material={materials.oceanShader4}
          />
        </group>
        <group
          position={[2, -1.422, 1.231]}
          rotation={[-0.061, 0, -Math.PI / 2]}
          scale={[0.505, 0.173, 0.505]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder17_phong2_0.geometry}
            material={materials.phong2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder17_lambert5_0.geometry}
            material={materials.lambert5}
          />
        </group>
        <group position={[0, 1.014, -3.522]} rotation={[-0.061, 0, 0]} scale={[1, 1.019, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere1_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere1_blinn9_0.geometry}
            material={materials.blinn9}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere1_oceanShader2_0.geometry}
            material={materials.oceanShader2}
          />
        </group>
        <group
          position={[0, 0.669, -1.364]}
          rotation={[-0.061, 1.309, 0]}
          scale={[1.161, 1.059, 1.161]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere7_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere7_blinn5_0.geometry}
            material={materials.blinn5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere7_oceanShader1_0.geometry}
            material={materials.oceanShader1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere7_blinn6_0.geometry}
            material={materials.blinn6}
          />
        </group>
        <group position={[0, -0.785, 0]} rotation={[-0.061, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube10_blinn1_0.geometry}
            material={materials.blinn1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube10_phong4_0.geometry}
            material={materials.phong4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube10_lambert5_0.geometry}
            material={materials.lambert5}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube21_blinn3_0.geometry}
          material={materials.blinn3}
          position={[-1.76, -0.968, -2.994]}
          rotation={[-0.061, 0, 0]}
          scale={[1, 0.484, 1.244]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere3_oceanShader3_0.geometry}
          material={materials.oceanShader3}
          position={[-1.588, -0.223, 2.695]}
          rotation={[-0.061, 0, 0]}
          scale={[0.287, 0.287, 0.083]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder23_blinn19_0.geometry}
          material={materials.blinn19}
          position={[2.987, -0.886, -1.729]}
          rotation={[-0.06, 0, 0]}
          scale={0.853}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere5_phong1_0.geometry}
          material={materials.phong1}
          position={[0.021, 0.701, 2.937]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere6_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.018, 0.731, 2.92]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere7_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.019, 0.701, 2.937]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere3_phong1_0.geometry}
          material={materials.phong1}
          position={[0.021, 0.67, 2.952]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere4_phong1_0.geometry}
          material={materials.phong1}
          position={[0.02, 0.731, 2.92]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder14_blinn10_0.geometry}
          material={materials.blinn10}
          position={[0.438, 0.355, 1.644]}
          rotation={[-0.061, 0, 0]}
          scale={[0.046, 0.192, 0.046]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere24_phong1_0.geometry}
          material={materials.phong1}
          position={[0.061, 0.728, 2.878]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere9_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.021, 0.639, 2.969]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCylinder3_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.89, 2.919]}
          rotation={[-1.644, 0, Math.PI]}
          scale={[-0.01, 0, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere16_phong1_0.geometry}
          material={materials.phong1}
          position={[0.064, 0.726, 2.853]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere23_phong1_0.geometry}
          material={materials.phong1}
          position={[0.066, 0.725, 2.829]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere44_lambert1_0.geometry}
          material={materials.lambert1}
          position={[-0.077, 0.628, 2.869]}
          rotation={[-0.073, 0, -0.308]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere45_lambert1_0.geometry}
          material={materials.lambert1}
          position={[-0.075, 0.625, 2.836]}
          rotation={[-0.073, 0, -0.308]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere25_phong1_0.geometry}
          material={materials.phong1}
          position={[0.067, 0.698, 2.887]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere42_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.072, 0.657, 2.834]}
          rotation={[-0.073, 0, -0.308]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere43_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.074, 0.66, 2.863]}
          rotation={[-0.073, 0, -0.308]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube13_blinn13_0.geometry}
          material={materials.blinn13}
          position={[-1.695, -0.947, -1.381]}
          rotation={[3.081, 0, Math.PI]}
          scale={[0.986, 0.074, 0.986]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube11_blinn13_0.geometry}
          material={materials.blinn13}
          position={[-2.155, -1.358, -1.355]}
          rotation={[3.081, 0, Math.PI]}
          scale={[0.986, 0.074, 0.986]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere11_oceanShader3_0.geometry}
          material={materials.oceanShader3}
          position={[-1.13, -0.626, -4.456]}
          rotation={[-0.061, 0, 0]}
          scale={[0.147, 0.147, 0.043]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere10_oceanShader3_0.geometry}
          material={materials.oceanShader3}
          position={[-1.552, -0.626, -4.456]}
          rotation={[-0.061, 0, 0]}
          scale={[0.147, 0.147, 0.043]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere9_oceanShader3_0.geometry}
          material={materials.oceanShader3}
          position={[1.632, -0.626, -4.456]}
          rotation={[-0.061, 0, 0]}
          scale={[0.147, 0.147, 0.043]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder19_phong2_0.geometry}
          material={materials.phong2}
          position={[-2, -1.355, -2.971]}
          rotation={[-0.061, 0, -Math.PI / 2]}
          scale={[0.569, 0.195, 0.569]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube20_blinn3_0.geometry}
          material={materials.blinn3}
          position={[1.734, -0.968, -2.994]}
          rotation={[-0.061, 0, 0]}
          scale={[1, 0.484, 1.244]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube9_blinn10_0.geometry}
          material={materials.blinn10}
          position={[0, 0.344, 1.096]}
          rotation={[-0.061, 0, 0]}
          scale={[1.167, 0.563, 1.312]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube25_blinn13_0.geometry}
          material={materials.blinn13}
          position={[-2.26, -1.082, -0.933]}
          rotation={[1.51, -0.598, Math.PI]}
          scale={[0.082, 0.071, 0.747]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere39_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.066, 0.727, 2.853]}
          rotation={[-0.073, 0, -0.308]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere40_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.068, 0.691, 2.858]}
          rotation={[-0.073, 0, -0.308]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere41_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.069, 0.69, 2.831]}
          rotation={[-0.073, 0, -0.308]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere37_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.056, 0.635, 2.94]}
          rotation={[-0.073, 0, -0.216]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere38_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.064, 0.725, 2.829]}
          rotation={[-0.073, 0, -0.308]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube7_blinn12_0.geometry}
          material={materials.blinn12}
          position={[-1.127, -1.106, 2.884]}
          rotation={[-1.546, -Math.PI / 2, 0]}
          scale={[0.553, 0.253, 0.448]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder7_phong1_0.geometry}
          material={materials.phong1}
          position={[0.438, -0.476, 2.953]}
          rotation={[-0.061, 0, 0]}
          scale={[0.06, 0.458, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube29_blinn18_0.geometry}
          material={materials.blinn18}
          position={[0, -1.202, 3.078]}
          rotation={[-0.062, 0, 0]}
          scale={[0.873, 0.428, 0.031]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCube4_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.776, 2.909]}
          rotation={[-0.073, 0, 0]}
          scale={[0.103, 0.033, 0.043]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCube5_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.04, 0.778, 2.92]}
          rotation={[-0.073, 0, 0]}
          scale={[0.03, 0.033, 0.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder26_blinn19_0.geometry}
          material={materials.blinn19}
          position={[1.832, -0.631, 0.003]}
          rotation={[-0.06, 0, 0]}
          scale={0.523}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube30_blinn18_0.geometry}
          material={materials.blinn18}
          position={[0, -1.168, -4.73]}
          rotation={[2.977, -0.001, 3.142]}
          scale={[0.873, 0.428, 0.031]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere6_oceanShader3_0.geometry}
          material={materials.oceanShader3}
          position={[1, -0.223, 2.695]}
          rotation={[-0.061, 0, 0]}
          scale={[0.216, 0.216, 0.062]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere5_oceanShader3_0.geometry}
          material={materials.oceanShader3}
          position={[-0.956, -0.223, 2.695]}
          rotation={[-0.061, 0, 0]}
          scale={[0.216, 0.216, 0.062]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere12_phong1_0.geometry}
          material={materials.phong1}
          position={[0.049, 0.699, 2.914]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere13_phong1_0.geometry}
          material={materials.phong1}
          position={[0.051, 0.667, 2.928]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere14_phong1_0.geometry}
          material={materials.phong1}
          position={[0.056, 0.635, 2.94]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere8_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.019, 0.67, 2.952]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere11_phong1_0.geometry}
          material={materials.phong1}
          position={[0.048, 0.73, 2.902]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder9_blinn10_0.geometry}
          material={materials.blinn10}
          position={[-0.423, 0.355, 1.644]}
          rotation={[-0.061, 0, 0]}
          scale={[0.046, 0.192, 0.046]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder20_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0.015, -1.355, -2.971]}
          rotation={[-0.061, 0, -Math.PI / 2]}
          scale={[0.249, 1.981, 0.249]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube16_blinn13_0.geometry}
          material={materials.blinn13}
          position={[0, -1.127, -4.499]}
          rotation={[-1.695, 0, -Math.PI]}
          scale={[4.254, 0.319, 0.535]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube24_blinn4_0.geometry}
          material={materials.blinn4}
          position={[1.704, -0.947, -1.381]}
          rotation={[-0.061, 0, 0]}
          scale={[0.986, 0.074, 0.986]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder10_blinn10_0.geometry}
          material={materials.blinn10}
          position={[-0.252, 0.355, 1.644]}
          rotation={[-0.061, 0, 0]}
          scale={[0.046, 0.192, 0.046]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube26_blinn13_0.geometry}
          material={materials.blinn13}
          position={[-1.957, -1.165, -1.367]}
          rotation={[3.081, 0, Math.PI]}
          scale={[0.986, 0.074, 0.986]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube14_blinn4_0.geometry}
          material={materials.blinn4}
          position={[2.269, -1.081, -0.927]}
          rotation={[1.51, 0.598, 0]}
          scale={[0.082, 0.071, 0.747]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder11_blinn10_0.geometry}
          material={materials.blinn10}
          position={[-0.081, 0.355, 1.644]}
          rotation={[-0.061, 0, 0]}
          scale={[0.046, 0.192, 0.046]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder1_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.423, -0.476, 2.953]}
          rotation={[-0.061, 0, 0]}
          scale={[0.06, 0.458, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder13_blinn10_0.geometry}
          material={materials.blinn10}
          position={[0.268, 0.355, 1.644]}
          rotation={[-0.061, 0, 0]}
          scale={[0.046, 0.192, 0.046]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube5_blinn12_0.geometry}
          material={materials.blinn12}
          position={[0, -1.112, 2.785]}
          rotation={[-1.546, 0, 0]}
          scale={[4.254, 0.319, 0.717]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.252, -0.476, 2.953]}
          rotation={[-0.061, 0, 0]}
          scale={[0.06, 0.458, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_phong1_0.geometry}
          material={materials.phong1}
          position={[0.089, -0.476, 2.953]}
          rotation={[-0.061, 0, 0]}
          scale={[0.06, 0.458, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube8_phong1_0.geometry}
          material={materials.phong1}
          position={[0.015, -0.295, 2.951]}
          rotation={[-0.061, 0, 0]}
          scale={[1.322, 2.056, 0.118]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder4_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.081, -0.476, 2.953]}
          rotation={[-0.061, 0, 0]}
          scale={[0.06, 0.458, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere13_phongE1_0.geometry}
          material={materials.phongE1}
          position={[0, 2.513, -3.626]}
          rotation={[-0.079, 0, 0]}
          scale={0.055}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCylinder1_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.041, 0.802, 2.972]}
          rotation={[-2.034, 0, 0]}
          scale={[0.005, 0.047, 0.006]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCylinder2_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.889, 2.895]}
          rotation={[-1.644, 0, 0]}
          scale={[0.004, 0.038, 0.005]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere2_phong1_0.geometry}
          material={materials.phong1}
          position={[0.022, 0.639, 2.969]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere1_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.864, 2.845]}
          rotation={[-0.073, 0, 0]}
          scale={[0.049, 0.046, 0.049]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCube6_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.883, 2.879]}
          rotation={[-0.073, 0, 0]}
          scale={[0.025, 0.037, 0.033]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere2_oceanShader3_0.geometry}
          material={materials.oceanShader3}
          position={[1.632, -0.223, 2.695]}
          rotation={[-0.061, 0, 0]}
          scale={[0.287, 0.287, 0.083]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube19_blinn2_0.geometry}
          material={materials.blinn2}
          position={[0, -0.236, 2.606]}
          rotation={[-0.061, 0, 0]}
          scale={[4.623, 0.798, 0.267]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube18_blinn13_0.geometry}
          material={materials.blinn13}
          position={[1.127, -1.133, -4.598]}
          rotation={[1.395, Math.PI / 2, 0]}
          scale={[0.413, 0.253, 0.448]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube28_blinn4_0.geometry}
          material={materials.blinn4}
          position={[2.164, -1.358, -1.355]}
          rotation={[-0.061, 0, 0]}
          scale={[0.986, 0.074, 0.986]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCube7_phong1_0.geometry}
          material={materials.phong1}
          position={[0.06, 0.788, 2.824]}
          rotation={[-0.037, 0.008, 0.253]}
          scale={[0.001, 0.049, 0.008]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCube8_phong1_0.geometry}
          material={materials.phong1}
          position={[0.06, 0.789, 2.841]}
          rotation={[-0.122, -0.014, 0.253]}
          scale={[0.001, 0.049, 0.008]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCube10_phong1_0.geometry}
          material={materials.phong1}
          position={[0.057, 0.791, 2.864]}
          rotation={[-0.129, -0.317, 0.263]}
          scale={[0.001, 0.049, 0.008]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere15_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.041, 0.828, 3.021]}
          rotation={[1.052, 0, 0]}
          scale={[0.011, 0.009, 0.012]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCylinder11_phong1_0.geometry}
          material={materials.phong1}
          position={[0.04, 0.783, 2.934]}
          rotation={[1.143, 0, -0.003]}
          scale={[0.008, 0.002, 0.009]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere28_phong1_0.geometry}
          material={materials.phong1}
          position={[0.07, 0.69, 2.831]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere29_phong1_0.geometry}
          material={materials.phong1}
          position={[0.071, 0.691, 2.858]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere30_phong1_0.geometry}
          material={materials.phong1}
          position={[0.076, 0.657, 2.834]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere26_phong1_0.geometry}
          material={materials.phong1}
          position={[0.071, 0.662, 2.897]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere27_phong1_0.geometry}
          material={materials.phong1}
          position={[0.074, 0.632, 2.908]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCylinder6_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.891, 2.92]}
          rotation={[-1.644, 0, Math.PI]}
          scale={[-0.01, 0, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCylinder7_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.891, 2.924]}
          rotation={[-1.644, 0, Math.PI]}
          scale={[-0.007, 0, 0.008]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCylinder8_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.891, 2.922]}
          rotation={[-1.644, 0, Math.PI]}
          scale={[-0.009, 0, 0.009]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCylinder4_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.89, 2.917]}
          rotation={[-1.644, 0, Math.PI]}
          scale={[-0.009, 0, 0.009]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCylinder5_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.89, 2.915]}
          rotation={[-1.644, 0, Math.PI]}
          scale={[-0.007, 0, 0.008]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder24_blinn19_0.geometry}
          material={materials.blinn19}
          position={[-0.233, -0.886, -1.729]}
          rotation={[-0.06, 0, 0]}
          scale={0.853}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere8_phongE1_0.geometry}
          material={materials.phongE1}
          position={[0, 2.213, -1.46]}
          rotation={[-0.079, 0, 0]}
          scale={0.055}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere12_oceanShader3_0.geometry}
          material={materials.oceanShader3}
          position={[1.125, -0.626, -4.456]}
          rotation={[-0.061, 0, 0]}
          scale={[0.147, 0.147, 0.043]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere36_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.055, 0.667, 2.928]}
          rotation={[-0.073, 0, -0.216]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCube1_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.606, 2.895]}
          rotation={[-0.073, 0, 0]}
          scale={[0.176, 0.02, 0.225]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCylinder10_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.034, 0.898, 2.841]}
          rotation={[-0.073, 0, 0.728]}
          scale={[0.006, 0.001, 0.006]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCube2_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.676, 2.89]}
          rotation={[-0.073, 0, 0]}
          scale={[0.167, 0.131, 0.212]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCube3_phong1_0.geometry}
          material={materials.phong1}
          position={[0.039, 0.778, 2.92]}
          rotation={[-0.073, 0, 0]}
          scale={[0.03, 0.033, 0.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere10_phong1_0.geometry}
          material={materials.phong1}
          position={[0, 0.893, 2.954]}
          rotation={[1.497, 0, 0]}
          scale={[0.011, 0.014, 0.012]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pCylinder9_phong1_0.geometry}
          material={materials.phong1}
          position={[0.034, 0.899, 2.841]}
          rotation={[-0.073, 0, -0.731]}
          scale={[0.006, 0.001, 0.006]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube31_blinn18_0.geometry}
          material={materials.blinn18}
          position={[2.135, -0.491, -1.498]}
          rotation={[-0.062, Math.PI / 2, 0]}
          scale={[0.281, 0.089, 0.01]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder12_blinn10_0.geometry}
          material={materials.blinn10}
          position={[0.089, 0.355, 1.644]}
          rotation={[-0.061, 0, 0]}
          scale={[0.046, 0.192, 0.046]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder8_phong1_0.geometry}
          material={materials.phong1}
          position={[0.268, -0.476, 2.953]}
          rotation={[-0.061, 0, 0]}
          scale={[0.06, 0.458, 0.06]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder16_phong2_0.geometry}
          material={materials.phong2}
          position={[-2, -1.422, 1.231]}
          rotation={[-0.061, 0, -Math.PI / 2]}
          scale={[0.505, 0.173, 0.505]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube27_blinn13_0.geometry}
          material={materials.blinn13}
          position={[-2.26, -1.135, -1.814]}
          rotation={[1.51, -0.598, Math.PI]}
          scale={[0.082, 0.071, 0.747]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCone1_blinn15_0.geometry}
          material={materials.blinn15}
          position={[-0.488, 1.92, -1.329]}
          rotation={[-1.632, 0, 0]}
          scale={[0.467, 0.613, 0.467]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube15_blinn4_0.geometry}
          material={materials.blinn4}
          position={[2.269, -1.135, -1.808]}
          rotation={[1.51, 0.598, 0]}
          scale={[0.082, 0.071, 0.747]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube12_blinn4_0.geometry}
          material={materials.blinn4}
          position={[1.966, -1.165, -1.367]}
          rotation={[-0.061, 0, 0]}
          scale={[0.986, 0.074, 0.986]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube17_blinn13_0.geometry}
          material={materials.blinn13}
          position={[-1.151, -1.133, -4.598]}
          rotation={[1.395, Math.PI / 2, 0]}
          scale={[0.413, 0.253, 0.448]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube6_blinn12_0.geometry}
          material={materials.blinn12}
          position={[1.151, -1.106, 2.884]}
          rotation={[-1.546, -Math.PI / 2, 0]}
          scale={[0.553, 0.253, 0.448]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube3_blinn14_0.geometry}
          material={materials.blinn14}
          position={[-1.791, 0.512, -3.821]}
          rotation={[-0.061, 0, 0]}
          scale={[0.183, 1.704, 1.317]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube4_blinn13_0.geometry}
          material={materials.blinn13}
          position={[0, 1.402, -4.854]}
          rotation={[0.153, 0, 0]}
          scale={[4.726, 0.237, 0.889]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere33_phong1_0.geometry}
          material={materials.phong1}
          position={[0.079, 0.628, 2.869]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere34_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.046, 0.73, 2.902]}
          rotation={[-0.073, 0, -0.216]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere35_phong1_0.geometry}
          material={materials.phong1}
          position={[-0.051, 0.7, 2.914]}
          rotation={[-0.073, 0, -0.216]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere31_phong1_0.geometry}
          material={materials.phong1}
          position={[0.074, 0.659, 2.863]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dalek_0005pSphere32_phong1_0.geometry}
          material={materials.phong1}
          position={[0.081, 0.626, 2.836]}
          rotation={[-0.073, 0, 0]}
          scale={[0.011, 0.012, 0.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder25_blinn19_0.geometry}
          material={materials.blinn19}
          position={[-0.125, -0.631, 0.003]}
          rotation={[-0.06, 0, 0]}
          scale={0.523}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.typeMesh1_phongE2_0.geometry}
        material={materials.phongE2}
        position={[23.05, -4.086, 14.222]}
        rotation={[-1.623, 1.401, Math.PI / 2]}
        scale={[0.233, 0.233, 0.717]}
      />
    </group>
  )
}

useGLTF.preload('/the_homer_from_the_simpsons_low-poly.glb')


